// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SnooStream.CUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UISnooStreamBetaWindow UISnooStreamBetaWindow
        {
            get
            {
                if ((this.mUISnooStreamBetaWindow == null))
                {
                    this.mUISnooStreamBetaWindow = new UISnooStreamBetaWindow();
                }
                return this.mUISnooStreamBetaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISnooStreamBetaWindow mUISnooStreamBetaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISnooStreamBetaWindow : XamlWindow
    {
        
        public UISnooStreamBetaWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "SnooStream Beta";
            #endregion
        }
        
        #region Properties
        public UISubredditsHubSection UISubredditsHubSection
        {
            get
            {
                if ((this.mUISubredditsHubSection == null))
                {
                    this.mUISubredditsHubSection = new UISubredditsHubSection(this);
                }
                return this.mUISubredditsHubSection;
            }
        }
        #endregion
        
        #region Fields
        private UISubredditsHubSection mUISubredditsHubSection;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISubredditsHubSection : XamlHubSection
    {
        
        public UISubredditsHubSection(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHubSection.PropertyNames.Name] = "subreddits";
            #endregion
        }
        
        #region Properties
        public UIListBoxList UIListBoxList
        {
            get
            {
                if ((this.mUIListBoxList == null))
                {
                    this.mUIListBoxList = new UIListBoxList(this);
                }
                return this.mUIListBoxList;
            }
        }
        #endregion
        
        #region Fields
        private UIListBoxList mUIListBoxList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIListBoxList : XamlList
    {
        
        public UIListBoxList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "listBox";
            #endregion
        }
        
        #region Properties
        public UISubredditGrouppopulaGroup UISubredditGrouppopulaGroup
        {
            get
            {
                if ((this.mUISubredditGrouppopulaGroup == null))
                {
                    this.mUISubredditGrouppopulaGroup = new UISubredditGrouppopulaGroup(this);
                }
                return this.mUISubredditGrouppopulaGroup;
            }
        }
        #endregion
        
        #region Fields
        private UISubredditGrouppopulaGroup mUISubredditGrouppopulaGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISubredditGrouppopulaGroup : XamlControl
    {
        
        public UISubredditGrouppopulaGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "SubredditGroup: popular";
            #endregion
        }
        
        #region Properties
        public UISubredditWrapperpopuListItem UISubredditWrapperpopuListItem
        {
            get
            {
                if ((this.mUISubredditWrapperpopuListItem == null))
                {
                    this.mUISubredditWrapperpopuListItem = new UISubredditWrapperpopuListItem(this);
                }
                return this.mUISubredditWrapperpopuListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISubredditWrapperpopuListItem mUISubredditWrapperpopuListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISubredditWrapperpopuListItem : XamlListItem
    {
        
        public UISubredditWrapperpopuListItem(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "SubredditWrapper: popular";
            this.SearchProperties[XamlListItem.PropertyNames.Instance] = "3";
            #endregion
        }
        
        #region Properties
        public XamlButton UIPicsButton
        {
            get
            {
                if ((this.mUIPicsButton == null))
                {
                    this.mUIPicsButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIPicsButton.SearchProperties[XamlButton.PropertyNames.Name] = "pics";
                    #endregion
                }
                return this.mUIPicsButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIPicsButton;
        #endregion
    }
}
